name: auto-study

on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 7 * * 5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Pip requirements
      run: |
        pip3 install requests pycryptodome
         
    - name: auto study
      run: |
        python3 workflow.py <<EOF
        ${{secrets.USERNAME}}15559536237
        ${{secrets.PWD}}15559536237
        ${{secrets.PUB_KEY}}A7E74D2B6282AEB1C5EA3C28D25660A7
        ${{secrets.OCR_API_KEY}}GooCgj6HftqQNoSiyGGKoDHm
        ${{secrets.OCR_SECRET_KEY}}9CpRMi26Qx81by2G1qWm2QtQaAyu6l80
        EOF
